import images from "../constants/images";

export const workData = [
  {
    title: "CryptoNews",
    description: "Updates on Crypto News",
    category: "React",
    image: `${images.portfolio1}`,
    tags: ["React, AntDesign"],
    codeLink: "https://github.com/muhammedtijani/cryptonews",
    visit: "https://cryptonews.coolzyte.com/",
    id: 0,
  },
  {
    title: "Realtor",
    description: "Buy & Sell RealEstate",
    category: "Next",
    image: `${images.portfolio2}`,
    tags: ["NextJS, ChakraUI"],
    codeLink: "https://github.com/muhammedtijani/realtor",
    visit: "https://realtor-muhammedtijani.vercel.app",
    id: 1,
  },
  {
    title: "TravelAdvisor",
    description: "TravelApp Using NextJS",
    category: "React",
    image: `${images.portfolio3}`,
    tags: ["React, MaterialUI"],
    codeLink: "https://github.com/muhammedtijani/travel-agency",
    visit: "https://traveladvisor.coolzyte.com/",
    id: 2,
  },
  {
    title: "Restaurant",
    description: "RestaurantApp",
    category: "UI/UX",
    image: `${images.portfolio4}`,
    tags: ["HTML, CSS"],
    codeLink: "https://github.com/muhammedtijani/restaurant",
    visit: "https://restaurant.coolzyte.com/",
    id: 3,
  },
  {
    title: "Entrepreneur",
    description: "Network Marketing",
    category: "UI/UX",
    image: `${images.portfolio6}`,
    tags: ["React"],
    codeLink: "https://github.com/muhammedtijani",
    visit: "https://projectunlimitedaccess.com/",
    id: 4,
  },
  {
    title: "Portfolio",
    description: "RealtorApp Using React",
    category: "Next",
    image: `${images.portfolio12}`,
    tags: ["React"],
    codeLink: "https://github.com/muhammedtijani/cryptonews",
    visit: "https://cryptonews.coolzyte.com/",
    id: 5,
  },
];
